"""Typed records shared by data ingestion, transformation, and versioning."""

from datetime import datetime, timedelta
import hashlib
from pathlib import PurePosixPath
import re
from typing import Literal
import unicodedata

from pydantic import BaseModel, Field, HttpUrl, TypeAdapter, field_validator, model_validator


_HTTP_URL = TypeAdapter(HttpUrl)


class SeedRecord(BaseModel):
    """Raw phishing seed collected from a trusted source."""

    text: str = Field(
        min_length=10,
        description="Raw message text with natural code-switching",
    )
    source_url: str = Field(description="Source URL for provenance tracking")
    scrape_timestamp: str = Field(description="ISO 8601 timestamp of scrape")
    raw_label_hint: str | None = Field(
        default=None,
        description="Optional initial threat classification hint",
    )


RecordUnit = Literal[
    "incident_report",
    "verbatim_message_example",
    "editorial_advisory",
    "threat_indicator",
    "dataset_row",
]
AccessMethod = Literal["download", "documented_api", "requests_bs4", "playwright"]
RightsStatus = Literal["allowed", "forbidden", "unknown"]
RedactionState = Literal["not_needed", "redacted", "verified_source_anonymized"]


class ProvenancedSeedRecord(SeedRecord):
    """A public real-source seed with explicit rights and lineage metadata.

    This is intentionally a seed contract, not a :class:`DatasetRecord`. In
    particular it has no project label, risk tier, or generated explanation,
    so collecting evidence cannot silently promote it into training data.
    """

    data_origin: Literal["real_public"]
    record_unit: RecordUnit
    canonical_url: str = Field(min_length=8)
    publisher: str = Field(min_length=2)
    native_id: str | None
    access_method: AccessMethod
    collection_status: RightsStatus
    redistribution_status: RightsStatus
    rights_url: str = Field(min_length=8)
    retrieved_at: str = Field(min_length=10)
    content_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    redaction_state: RedactionState
    contributing_urls: list[str] = Field(min_length=1)
    duplicate_count: int = Field(ge=0)
    provenance_confidence: Literal["high", "medium", "low"]

    @field_validator("source_url", "canonical_url", "rights_url")
    @classmethod
    def require_canonical_http_url(cls, value: str) -> str:
        return str(_HTTP_URL.validate_python(value))

    @field_validator("contributing_urls")
    @classmethod
    def require_canonical_contributing_urls(cls, values: list[str]) -> list[str]:
        return [str(_HTTP_URL.validate_python(value)) for value in values]

    @field_validator("scrape_timestamp", "retrieved_at")
    @classmethod
    def require_canonical_utc_timestamp(cls, value: str) -> str:
        try:
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError as error:
            raise ValueError("provenance timestamp must be valid ISO 8601") from error
        if parsed.tzinfo is None or parsed.utcoffset() != timedelta(0):
            raise ValueError("provenance timestamp must use an explicit UTC offset")
        return parsed.isoformat().replace("+00:00", "Z")

    @model_validator(mode="after")
    def validate_real_public_contract(self) -> "ProvenancedSeedRecord":
        if self.raw_label_hint is not None:
            raise ValueError("raw_label_hint must stay null for newly acquired public records")

        normalized = unicodedata.normalize("NFC", self.text).casefold().strip()
        normalized = re.sub(r"\s+", " ", normalized)
        expected_hash = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        if self.content_sha256 != expected_hash:
            raise ValueError("content_sha256 does not match normalized text")

        return self


class DatasetRecord(BaseModel):
    """A processed seven-field record with explainability artifacts."""

    text: str = Field(min_length=10, description="Raw message text")
    label: Literal[
        "bank_impersonation",
        "zalo_social_engineering",
        "task_scam",
        "benign",
    ] = Field(description="Precise threat classification")
    risk_tier: Literal["benign", "suspicious", "high-risk"] = Field(
        description=(
            "Contextual severity tier - generated by Teacher model, not derived from label"
        )
    )
    suspicious_spans: list[str] = Field(
        default_factory=list,
        description=(
            "Exact substrings for anomaly localization (URLs, urgency phrases, etc.)"
        ),
    )
    xai_explanation: str = Field(
        min_length=20,
        description="Teacher model's localized explanation for user-facing XAI output",
    )
    source: Literal[
        "ncsc_seed",
        "synthetic_claude",
        "synthetic_gemini",
        "synthetic_openrouter",
        "synthetic_deepseek",
        "synthetic_openai_compatible",
    ] = Field(description="Data provenance tag")
    seed_id: str = Field(
        description="Link back to originating seed record for split governance"
    )


class ManifestFile(BaseModel):
    """Metadata for a single dataset file in a versioned release."""

    sha256: str = Field(pattern=r"^[0-9a-f]{64}$", description="File integrity hash")
    records: int = Field(ge=0, description="Number of records in file")
    bytes: int = Field(ge=0, description="File size in bytes")


class ManifestEntry(BaseModel):
    """Version manifest for a reproducible dataset release."""

    version: str = Field(description="Semantic version tag (e.g., v1.0.0)")
    build_timestamp: str = Field(description="ISO 8601 build time")
    git_commit: str | None = Field(
        default=None,
        description="Git commit SHA for reproducibility",
    )
    files: dict[str, ManifestFile] = Field(
        default_factory=dict,
        description="Map of filename -> file metadata",
    )

    @field_validator("files")
    @classmethod
    def require_bounded_jsonl_members(
        cls, value: dict[str, ManifestFile]
    ) -> dict[str, ManifestFile]:
        for member in value:
            path = PurePosixPath(member)
            if (
                not member
                or "\\" in member
                or ":" in member
                or path.is_absolute()
                or path.as_posix() != member
                or any(part in {"", ".", ".."} for part in path.parts)
                or path.suffix != ".jsonl"
            ):
                raise ValueError("manifest members must be normalized relative JSONL paths")
        return value


__all__ = (
    "SeedRecord",
    "ProvenancedSeedRecord",
    "DatasetRecord",
    "ManifestFile",
    "ManifestEntry",
    "RecordUnit",
    "AccessMethod",
    "RightsStatus",
    "RedactionState",
)
