"""
Pydantic schemas for the Vietnamese phishing detection data pipeline.

These schemas enforce the XAI-optimized JSONL contract at every pipeline stage,
from seed scraping through synthetic generation to final dataset splits.
"""

from pydantic import BaseModel, Field
from typing import Literal


class SeedRecord(BaseModel):
    """
    Raw phishing seed scraped from NCSC or other trusted sources.
    
    Represents unprocessed threat examples that will be expanded into
    synthetic training data. Must preserve natural code-switching and
    Vietnamese SMS/social media linguistic patterns.
    """
    text: str = Field(min_length=10, description="Raw message text with natural code-switching")
    source_url: str = Field(description="Source URL for provenance tracking")
    scrape_timestamp: str = Field(description="ISO 8601 timestamp of scrape")
    raw_label_hint: str | None = Field(default=None, description="Optional initial threat classification hint")


class DatasetRecord(BaseModel):
    """
    Fully processed training/evaluation record with XAI-optimized structure.
    
    Each record includes explainability artifacts (suspicious spans, reasoning)
    to support downstream instruction tuning for user-facing threat explanations.
    """
    text: str = Field(min_length=10, description="Raw message text")
    label: Literal["bank_impersonation", "zalo_social_engineering", "task_scam", "benign"] = Field(
        description="Precise threat classification"
    )
    risk_tier: Literal["benign", "suspicious", "high-risk"] = Field(
        description="Contextual severity tier - generated by Teacher model, not derived from label"
    )
    suspicious_spans: list[str] = Field(
        default_factory=list,
        description="Exact substrings for anomaly localization (URLs, urgency phrases, etc.)"
    )
    xai_explanation: str = Field(
        min_length=20,
        description="Teacher model's localized explanation for user-facing XAI output"
    )
    source: Literal[
        "ncsc_seed",
        "synthetic_claude",
        "synthetic_gemini",
        "synthetic_openrouter",
        "synthetic_deepseek",
        "synthetic_openai_compatible",
    ] = Field(
        description="Data provenance tag"
    )
    seed_id: str = Field(description="Link back to originating seed record for split governance")


class ManifestFile(BaseModel):
    """Metadata for a single dataset file in a versioned release."""
    sha256: str = Field(description="File integrity hash")
    records: int = Field(description="Number of records in file")
    bytes: int = Field(description="File size in bytes")


class ManifestEntry(BaseModel):
    """
    Version manifest for reproducible dataset releases.
    
    Tracks git commit, build timestamp, and file hashes to ensure
    mathematical integrity verification before any LoRA fine-tuning run.
    """
    version: str = Field(description="Semantic version tag (e.g., v1.0.0)")
    build_timestamp: str = Field(description="ISO 8601 build time")
    git_commit: str | None = Field(default=None, description="Git commit SHA for reproducibility")
    files: dict[str, ManifestFile] = Field(
        default_factory=dict,
        description="Map of filename -> file metadata"
    )
