"""
Pydantic schemas for the Vietnamese phishing detection data pipeline.

These schemas enforce the XAI-optimized JSONL contract at every pipeline stage,
from seed scraping through synthetic generation to final dataset splits.
"""

import hashlib
import re
import unicodedata

from pydantic import BaseModel, Field, model_validator
from typing import Literal


class SeedRecord(BaseModel):
    """
    Raw phishing seed scraped from NCSC or other trusted sources.
    
    Represents unprocessed threat examples that will be expanded into
    synthetic training data. Must preserve natural code-switching and
    Vietnamese SMS/social media linguistic patterns.
    """
    text: str = Field(min_length=10, description="Raw message text with natural code-switching")
    source_url: str = Field(description="Source URL for provenance tracking")
    scrape_timestamp: str = Field(description="ISO 8601 timestamp of scrape")
    raw_label_hint: str | None = Field(default=None, description="Optional initial threat classification hint")


RecordUnit = Literal[
    "incident_report",
    "verbatim_message_example",
    "editorial_advisory",
    "threat_indicator",
    "dataset_row",
]
AccessMethod = Literal["download", "documented_api", "requests_bs4", "playwright"]
RightsStatus = Literal["allowed", "forbidden", "unknown"]
RedactionState = Literal["not_needed", "redacted", "verified_source_anonymized"]


class ProvenancedSeedRecord(SeedRecord):
    """A public real-source seed with explicit rights and lineage metadata.

    This is intentionally a seed contract, not a :class:`DatasetRecord`.  In
    particular it has no project label, risk tier, or generated explanation,
    so collecting evidence cannot silently promote it into training data.
    """

    data_origin: Literal["real_public"]
    record_unit: RecordUnit
    canonical_url: str = Field(min_length=8)
    publisher: str = Field(min_length=2)
    native_id: str | None
    access_method: AccessMethod
    collection_status: RightsStatus
    redistribution_status: RightsStatus
    rights_url: str = Field(min_length=8)
    retrieved_at: str = Field(min_length=10)
    content_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    redaction_state: RedactionState
    contributing_urls: list[str] = Field(min_length=1)
    duplicate_count: int = Field(ge=0)
    provenance_confidence: Literal["high", "medium", "low"]

    @model_validator(mode="after")
    def validate_real_public_contract(self) -> "ProvenancedSeedRecord":
        if self.raw_label_hint is not None:
            raise ValueError("raw_label_hint must stay null for newly acquired public records")

        normalized = unicodedata.normalize("NFC", self.text).casefold().strip()
        normalized = re.sub(r"\s+", " ", normalized)
        expected_hash = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        if self.content_sha256 != expected_hash:
            raise ValueError("content_sha256 does not match normalized text")

        if not self.retrieved_at.endswith(("Z", "+00:00")):
            raise ValueError("retrieved_at must be an explicit UTC timestamp")
        return self


class DatasetRecord(BaseModel):
    """
    Fully processed training/evaluation record with XAI-optimized structure.
    
    Each record includes explainability artifacts (suspicious spans, reasoning)
    to support downstream instruction tuning for user-facing threat explanations.
    """
    text: str = Field(min_length=10, description="Raw message text")
    label: Literal["bank_impersonation", "zalo_social_engineering", "task_scam", "benign"] = Field(
        description="Precise threat classification"
    )
    risk_tier: Literal["benign", "suspicious", "high-risk"] = Field(
        description="Contextual severity tier - generated by Teacher model, not derived from label"
    )
    suspicious_spans: list[str] = Field(
        default_factory=list,
        description="Exact substrings for anomaly localization (URLs, urgency phrases, etc.)"
    )
    xai_explanation: str = Field(
        min_length=20,
        description="Teacher model's localized explanation for user-facing XAI output"
    )
    source: Literal[
        "ncsc_seed",
        "synthetic_claude",
        "synthetic_gemini",
        "synthetic_openrouter",
        "synthetic_deepseek",
        "synthetic_openai_compatible",
    ] = Field(
        description="Data provenance tag"
    )
    seed_id: str = Field(description="Link back to originating seed record for split governance")


class ManifestFile(BaseModel):
    """Metadata for a single dataset file in a versioned release."""
    sha256: str = Field(description="File integrity hash")
    records: int = Field(description="Number of records in file")
    bytes: int = Field(description="File size in bytes")


class ManifestEntry(BaseModel):
    """
    Version manifest for reproducible dataset releases.
    
    Tracks git commit, build timestamp, and file hashes to ensure
    mathematical integrity verification before any LoRA fine-tuning run.
    """
    version: str = Field(description="Semantic version tag (e.g., v1.0.0)")
    build_timestamp: str = Field(description="ISO 8601 build time")
    git_commit: str | None = Field(default=None, description="Git commit SHA for reproducibility")
    files: dict[str, ManifestFile] = Field(
        default_factory=dict,
        description="Map of filename -> file metadata"
    )
